version: 2.1

parameters:
  daily:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps: 
      - run: echo "hello"
  build-a:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hello there"

workflows:
  main-workflow:
    when: 
      not: <<pipeline.parameters.daily>>
    jobs:
      - build
  daily-workflow:
    when: <<pipeline.parameters.daily>> 
    jobs: 
      - build-a